### ISSUE TITLE
Might look at GRInflector for other ideas on how to approach this

### ISSUE THREAD

**Issue by pdebruic** [olekscode/SingularizePluralize#1]
I'm not trying to diminish the work you've done but this has been in production for years.  

https://github.com/SeasideSt/Grease/tree/master/repository/Grease-Core.package/GRInflector.class/class

AFAIK It doesn't singularize things like what you've put together does.  

In it they cache the rules in class vars so they aren't instantiated every time a string is pluralized. 

I wish the  Smalltalk ecosystem had better code searching for things that have already been made

**Comment by jecisc** [comment]
What might be great also would be to have it as a standalone project because here for example I need something to pluralize strings and I'm conflicted because Grease is in production for years but seems a little big "just" to pluralize some strings.

**Comment by jecisc** [comment]
So I guess I'll go for this project instead
